[package]
name = "rustws"
version = "0.1.0"
edition = "2024"


[dependencies]
axum = { version = "0.8.4", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
strum = { version = "0.27.2", features = ["derive"] }
sqlx = { version = "0.8.6", default-features = false, features = [
  "postgres",
  "migrate",
  "macros",
  "runtime-tokio",
  "uuid",
  "chrono",
] }
tokio = { version = "1.47.0", features = ["full"] }
uuid = { version = "1.17.0", features = ["v4", "serde"] }
thiserror = "2.0.12"

# HTTP and networking
reqwest = { version = "0.12.22", features = ["json", "blocking"] }
tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["fs", "trace"] }
serde_json = "1.0.141"

# Configuration
dotenv = "0.15.0"

# Template engine
tera = "1.20.0"

# Development tools
notify = "8.1.0"
tower-livereload = "0.9.6"

# Tracing dependencies
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "json"] }
chrono = { version = "0.4.41", features = ["serde"] }

# Authentication dependencies
argon2 = "0.5.3"
rand = "0.9.2"
base64 = "0.22.0"
tower-sessions-sqlx-store = { version = "0.15.0", features = ["postgres"] }
tower-sessions = { version = "0.14.0", features = ["private"] }
axum-login = "0.18.0"

# Lambda execution
wasmer = { version = "6.0.1", default-features = false, features = [
  "cranelift",
] }
