//! Lambda Function Macro Crate
//!
//! This crate provides the `lambda_fn!` macro that eliminates all WASM infrastructure
//! code, allowing developers to focus purely on business logic.
//!
//! # Example
//!
//! ```rust
//! use serde::{Deserialize, Serialize};
//! use lambda_fn_macro::lambda_fn;
//!
//! #[derive(Debug, Clone, Serialize, Deserialize)]
//! pub struct MyInput {
//!     pub message: String,
//!     pub count: i32,
//! }
//!
//! #[derive(Debug, Clone, Serialize, Deserialize)]
//! pub struct MyOutput {
//!     pub result: String,
//!     pub new_count: i32,
//! }
//!
//! lambda_fn! {
//!     input: MyInput,
//!     output: MyOutput,
//!     handler: |input: MyInput| -> MyOutput {
//!         MyOutput {
//!             result: format!("Processed: {}", input.message),
//!             new_count: input.count + 1,
//!         }
//!     }
//! }
//! ```

/// Macro to create a complete lambda function with WASM infrastructure
///
/// This macro generates all the necessary WASM boilerplate including:
/// - Memory management functions (`wasm_malloc`, `wasm_free_impl`)
/// - Handler function with pointer-based interface
/// - Serialization/deserialization logic
/// - Error handling
///
/// Users only need to define their input/output types and business logic.
#[macro_export]
macro_rules! lambda_fn {
    (
        input: $input_type:ty,
        output: $output_type:ty,
        handler: |$input_param:ident: $input_param_type:ty| -> $output_param_type:ty $handler_body:block
    ) => {
        // ===== WASM MEMORY MANAGEMENT =====

        /// Allocate memory in WASM that can be accessed by the host
        #[no_mangle]
        pub extern "C" fn wasm_malloc(size: usize) -> *mut u8 {
            let mut buf = Vec::with_capacity(size);
            let ptr = buf.as_mut_ptr();
            std::mem::forget(buf);
            ptr
        }

        /// Free memory allocated by wasm_malloc
        #[no_mangle]
        pub extern "C" fn wasm_free_impl(ptr: *mut u8, size: usize) {
            unsafe {
                let _ = Vec::from_raw_parts(ptr, 0, size);
            }
        }

        // ===== MAIN HANDLER FUNCTION =====

        /// Main handler function - GENERATED BY MACRO
        /// Handles all WASM interface complexity (pointers, serialization, etc.)
        #[no_mangle]
        pub extern "C" fn handler(
            ptr_in: *const u8,
            len_in: usize,
            ptr_out: *mut u8,
            max_out_len: usize,
        ) -> usize {
            // Deserialize input from WASM memory
            let input_slice = unsafe { std::slice::from_raw_parts(ptr_in, len_in) };
            let input: $input_type = match serde_json::from_slice(input_slice) {
                Ok(input) => input,
                Err(e) => {
                    // Create error response and serialize it
                    let error_msg = format!("Failed to deserialize input: {}", e);
                    let error_bytes = error_msg.as_bytes();
                    let copy_len = std::cmp::min(max_out_len, error_bytes.len());
                    unsafe {
                        std::ptr::copy_nonoverlapping(error_bytes.as_ptr(), ptr_out, copy_len);
                    }
                    return copy_len;
                }
            };

            // Call user's business logic function
            let output = lambda_fn_impl(input);

            // Serialize output to JSON
            let output_bytes = match serde_json::to_vec(&output) {
                Ok(bytes) => bytes,
                Err(e) => {
                    // Create error response and serialize it
                    let error_msg = format!("Failed to serialize output: {}", e);
                    let error_bytes = error_msg.as_bytes();
                    let copy_len = std::cmp::min(max_out_len, error_bytes.len());
                    unsafe {
                        std::ptr::copy_nonoverlapping(error_bytes.as_ptr(), ptr_out, copy_len);
                    }
                    return copy_len;
                }
            };

            // Copy output to WASM memory
            let copy_len = std::cmp::min(max_out_len, output_bytes.len());
            unsafe {
                std::ptr::copy_nonoverlapping(output_bytes.as_ptr(), ptr_out, copy_len);
            }
            copy_len
        }

        // ===== BUSINESS LOGIC FUNCTION =====

        /// User's business logic - PURE RUST, NO WASM CONCERNS
        fn lambda_fn_impl($input_param: $input_param_type) -> $output_param_type $handler_body
    };
}
