//! Hello World Lambda Function - Using lambda_fn! macro with HTTP and Schema Generation
//!
//! This demonstrates:
//! - Using the enhanced lambda_fn! macro with enable_http: true
//! - Making HTTP requests from WASM lambdas (auto-generated by macro)
//! - Automatic JSON schema generation for workflow validation
//! - Pure business logic without any WASM boilerplate

use lambda_fn_macro::lambda_fn;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

// ===== LAMBDA BUSINESS LOGIC =====

/// HelloWorld response structure
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct HelloWorld {
    pub text: String,
    pub count: isize,
    pub post: Option<Post>,
}

/// Example JSONPlaceholder post structure for HTTP demo
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema, Default)]
pub struct Post {
    pub id: u32,
    pub title: String,
    pub body: String,
    pub userId: u32,
}

// ===== LAMBDA IMPLEMENTATION USING MACRO =====

lambda_fn! {
    features: [http],
    handler: |input: HelloWorld| -> HelloWorld {
        // Validation
        if input.count > 50 {
            panic!("Count is too high");
        }


        // Business logic with HTTP request - pure Rust!
        let mut headers = HashMap::new();
        headers.insert("User-Agent".to_string(), "rustws-lambda/1.0".to_string());

        let request = Request {
            method: "GET".to_string(),
            url: "https://jsonplaceholder.typicode.com/posts/1".to_string(),
            headers,
            body: None,
        };

        match http_request(&request) {
            Ok(response) if response.is_success() => {
                // Try to parse the JSONPlaceholder API response using type-safe deserialization
                match response.json::<Post>() {
                    Ok(post) => HelloWorld {
                        text: format!(
                            "Processed: {} (original count: {}). Got post '{}' by user {}!",
                            input.text, input.count, post.title, post.userId
                        ),
                        count: input.count + 10,
                        post: None
                    },
                    Err(_) => HelloWorld {
                        text: format!(
                            "Processed: {} (original count: {}). Got HTTP response but couldn't parse JSON: {}",
                            input.text,
                            input.count,
                            response.text()
                        ),
                        count: input.count + 10,
                        post: None
                    },
                }
            }
            Ok(response) => HelloWorld {
                text: format!(
                    "Processed: {} (original count: {}). HTTP request failed with status: {}",
                    input.text,
                    input.count,
                    response.status()
                ),
                count: input.count + 10,
                post: None
            },
            Err(e) => HelloWorld {
                text: format!(
                    "Processed: {} (original count: {}). HTTP request error: {}",
                    input.text, input.count, e
                ),
                count: input.count + 10,
                post: None
            },
        }
    }
}

// ===== MACRO USAGE NOTES =====
//
// This lambda uses the enhanced lambda_fn! macro with `enable_http: true`.
// The macro automatically generates:
// - Request/Response structs with JsonSchema derives
// - http_request() function for easy HTTP calls
// - All WASM memory management and host function bindings
// - JSON schema export functions for workflow validation
//
// Benefits of using the macro:
// ✅ No boilerplate: Just business logic
// ✅ Type safety: Request/Response are strongly typed
// ✅ Schema generation: Automatic workflow validation support
// ✅ Error handling: Built-in serialization/deserialization
// ✅ HTTP support: Full HTTP client functionality
//
// Usage examples (all types auto-generated by macro):
//
// - Simple GET request:
//   let request = Request {
//       method: "GET".to_string(),
//       url: "https://api.example.com/data".to_string(),
//       headers: HashMap::new(),
//       body: None,
//   };
//   let response = http_request(&request)?;
//   let data: MyData = response.json()?;  // Type-safe!
//
// - POST with JSON:
//   let mut headers = HashMap::new();
//   headers.insert("Content-Type".to_string(), "application/json".to_string());
//   let request = Request {
//       method: "POST".to_string(),
//       url: "https://api.example.com/create".to_string(),
//       headers,
//       body: Some(serde_json::to_string(&my_data)?),
//   };
//   let response = http_request(&request)?;
//
// - Error handling:
//   match http_request(&request) {
//       Ok(response) if response.is_success() => {
//           // Handle 2xx responses
//       },
//       Ok(response) => {
//           // Handle error responses (4xx, 5xx)
//       },
//       Err(e) => {
//           // Handle network errors
//       }
//   }
